export const ADD_BANK_ACCOUNT = 'ADD_BANK_ACCOUNT';
export const ALL_BANK_ACCOUNTS = 'ALL_BANK_ACCOUNTS';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const  ALL_USERS = 'ALL_USERS';
